# This is a config for E2B sandbox template.
# You can use template ID (31hkb6ua8dij9umnarxy) or template name (pluffy-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("pluffy-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("pluffy-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('pluffy-nextjs-test-2')

team_id = "1c04d98b-5799-40f3-9521-ab6572e5e8a1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "pluffy-nextjs-test-2"
template_id = "31hkb6ua8dij9umnarxy"
